package service

import (
	"crypto/ed25519"
	"crypto/rand"
	"encoding/base64"
	"encoding/json"
	"errors"
	"os"
	"sync"
	"time"
)

// LicensePayload is the signed license content (short field names = obfuscation)
type LicensePayload struct {
	Ver  int    `json:"v"`    // version
	To   string `json:"t"`    // licensed_to
	MU   int    `json:"m_u"`  // max_users (obfuscated field name)
	Iss  string `json:"i"`    // issued_at
	Exp  string `json:"e"`    // expires_at
	Feat []string `json:"f"`  // features
	Sig  string `json:"s"`    // signature (base64)
}

// License states
const (
	LicStateFree    = "free"    // no license file → 20 users
	LicStateValid   = "valid"   // valid signed license
	LicStateTampered = "tampered" // invalid signature → 5 users penalty
)

// Default seat limits (obfuscated — never appear as plain literals)
const (
	_seatFree  = 20
	_seatPenal = 5
)

var (
	licMu     sync.RWMutex
	licState  = LicStateFree
	licMax    = _seatFree
	licTo     = ""
	licExpiry time.Time
	licErr    string

	// publicKey is the Ed25519 verification key embedded in the binary.
	// Generated by scripts/gen-license.go; the private half stays with the vendor.
	publicKey ed25519.PublicKey
)

// SetPublicKey injects the license verification key at startup
func SetPublicKey(pk ed25519.PublicKey) {
	licMu.Lock()
	defer licMu.Unlock()
	publicKey = pk
}

// LicenseMaxUsers returns the current seat limit
func LicenseMaxUsers() int {
	licMu.RLock()
	defer licMu.RUnlock()
	if licState == LicStateValid && licMax > 0 {
		return licMax
	}
	if licState == LicStateTampered {
		return _seatPenal
	}
	return _seatFree
}

// LicenseState returns current state for the admin panel
func LicenseState() (state, licensedTo, errMsg string, maxUsers int, expiry time.Time) {
	licMu.RLock()
	defer licMu.RUnlock()
	return licState, licTo, licErr, licMax, licExpiry
}

// LoadLicense reads and verifies license.key from path
func LoadLicense(path string) error {
	data, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			setState(LicStateFree, "", "", _seatFree, time.Time{})
			return nil
		}
		return err
	}
	return verifyLicense(data)
}

// verifyLicense checks the Ed25519 signature and applies the payload
func verifyLicense(data []byte) error {
	var payload LicensePayload
	if err := json.Unmarshal(data, &payload); err != nil {
		setState(LicStateTampered, "", "فرمت فایل لایسنس نامعتبر است", _seatPenal, time.Time{})
		return errors.New("invalid license format")
	}

	if publicKey == nil {
		setState(LicStateTampered, "", "کلید عمومی تنظیم نشده", _seatPenal, time.Time{})
		return errors.New("no public key")
	}

	sig, err := base64.StdEncoding.DecodeString(payload.Sig)
	if err != nil {
		setState(LicStateTampered, "", "امضای لایسنس نامعتبر است", _seatPenal, time.Time{})
		return errors.New("bad signature encoding")
	}

	// Signature covers the canonical payload (excluding the sig field)
	canonical, _ := json.Marshal(struct {
		V  int      `json:"v"`
		T  string   `json:"t"`
		MU int      `json:"m_u"`
		I  string   `json:"i"`
		E  string   `json:"e"`
		F  []string `json:"f"`
	}{payload.Ver, payload.To, payload.MU, payload.Iss, payload.Exp, payload.Feat})

	if !ed25519.Verify(publicKey, canonical, sig) {
		setState(LicStateTampered, "", "امضای دیجیتال تأیید نشد — فایل ممکن است دستکاری شده باشد", _seatPenal, time.Time{})
		return errors.New("invalid signature")
	}

	exp, err := time.Parse(time.RFC3339, payload.Exp)
	if err != nil {
		setState(LicStateTampered, "", "تاریخ انقضای لایسنس نامعتبر است", _seatPenal, time.Time{})
		return errors.New("bad expiry")
	}

	if time.Now().After(exp) {
		setState(LicStateTampered, payload.To, "لایسنس منقضی شده است", _seatPenal, exp)
		return errors.New("license expired")
	}

	setState(LicStateValid, payload.To, "", payload.MU, exp)
	return nil
}

// RemoveLicense deletes the license file → back to free (20 users)
func RemoveLicense(path string) error {
	if err := os.Remove(path); err != nil && !os.IsNotExist(err) {
		return err
	}
	setState(LicStateFree, "", "", _seatFree, time.Time{})
	return nil
}

func setState(state, to, errMsg string, maxUsers int, expiry time.Time) {
	licMu.Lock()
	defer licMu.Unlock()
	licState = state
	licTo = to
	licErr = errMsg
	licMax = maxUsers
	licExpiry = expiry
}

// GenerateKeyPair creates a new Ed25519 keypair (used by gen-license tool)
func GenerateKeyPair() (ed25519.PrivateKey, ed25519.PublicKey, error) {
	pub, priv, err := ed25519.GenerateKey(rand.Reader)
	return priv, pub, err
}

// SignLicense creates a signed license file (used by gen-license tool)
func SignLicense(priv ed25519.PrivateKey, licensedTo string, maxUsers int, expiry time.Time) ([]byte, error) {
	payload := LicensePayload{
		Ver: 1, To: licensedTo, MU: maxUsers,
		Iss: time.Now().UTC().Format(time.RFC3339),
		Exp: expiry.UTC().Format(time.RFC3339),
		Feat: []string{"chat", "files", "reactions"},
	}
	canonical, _ := json.Marshal(struct {
		V  int      `json:"v"`
		T  string   `json:"t"`
		MU int      `json:"m_u"`
		I  string   `json:"i"`
		E  string   `json:"e"`
		F  []string `json:"f"`
	}{payload.Ver, payload.To, payload.MU, payload.Iss, payload.Exp, payload.Feat})

	sig := ed25519.Sign(priv, canonical)
	payload.Sig = base64.StdEncoding.EncodeToString(sig)
	return json.MarshalIndent(payload, "", "  ")
}
