package service

import (
	"crypto/ed25519"
	"encoding/base64"
)

// khanPubKeyB64 is the Ed25519 public key for license verification.
// Generated by scripts/gen-license (public.key). The private key stays with the vendor.
var khanPubKeyB64 = "WsuoMPHX8Dz1a/JQZMy6lUMNqHneV94R94kAJwqJkgA="

func init() {
	pk, err := base64.StdEncoding.DecodeString(khanPubKeyB64)
	if err == nil {
		SetPublicKey(ed25519.PublicKey(pk))
	}
}
